substitutions = {
    'Allspice': {'Amount': '1 teaspoon', 'Substitution': '1/2 teaspoon cinnamon, 1/4 teaspoon ginger, and 1/4 teaspoon cloves'},
    'Arrowroot starch': {'Amount': '1 teaspoon', 'Substitution': '1 tablespoon flour OR 1 teaspoon cornstarch'},
    'Baking mix': {'Amount': '1 cup', 'Substitution': '1 cup pancake mix'},
    'Baking powder': {'Amount': '1 teaspoon', 'Substitution': '1/4 teaspoon baking soda plus 1/2 teaspoon cream of tartar OR 1/4 teaspoon baking soda plus 1/2 cup buttermilk (decrease liquid in recipe by 1/2 cup)'},
    'Baking soda': {'Amount': '1 teaspoon', 'Substitution': '4 teaspoons baking powder OR 1 teaspoon potassium bicarbonate and 1/3 teaspoon salt. NOTE: If the recipe calls for an acidic liquid such as sour cream, yogurt, buttermilk, vinegar, molasses, or citrus juice, you should replace it with the same amount of whole milk'},
    'Beer': {'Amount': '1 cup', 'Substitution': '1 cup nonalcoholic beer OR 1 cup chicken broth'},
    'Brandy': {'Amount': '1/4 cup', 'Substitution': '1 teaspoon imitation brandy extract plus enough water to make 1/4 cup'},
    'Bread crumbs': {'Amount': '1 cup', 'Substitution': '1 cup cracker crumbs OR 1 cup matzo meal OR 1 cup ground oats'},
    'Beef broth': {'Amount': '1 cup', 'Substitution': '1 bouillon cube plus 1 cup boiling water OR 1 tablespoon soy sauce plus enough water to make 1 cup OR 1 cup vegetable broth'},
    'Chicken broth': {'Amount': '1 cup', 'Substitution': '1 bouillon cube plus 1 cup boiling water OR 1 tablespoon soy sauce plus enough water to make 1 cup OR 1 cup vegetable broth'},
    'Brown sugar': {'Amount': '1 cup, packed', 'Substitution': '1 cup white sugar plus 1/4 cup molasses and decrease the liquid in recipe by 1/4 cup OR 1 cup white sugar OR 1 1/4 cups confectioners\' sugar'},
    'Salted Butter': {'Amount': '1 cup', 'Substitution': '1 cup margarine OR 1 cup shortening plus 1/2 teaspoon salt OR 7/8 cup vegetable oil plus 1/2 teaspoon salt OR 7/8 cup lard plus 1/2 teaspoon salt'},
    'Unsalted Butter': {'Amount': '1 cup', 'Substitution': '1 cup shortening OR 7/8 cup vegetable oil OR 7/8 cup lard'},
    'Buttermilk': {'Amount': '1 cup', 'Substitution': '1 cup yogurt OR 1 tablespoon lemon juice or vinegar plus enough milk to make 1 cup'},
    'Cheddar cheese': {'Amount': '1 cup shredded', 'Substitution': '1 cup shredded Colby cheddar OR 1 cup shredded Monterey Jack cheese'},
    'Chervil': {'Amount': '1 tablespoon chopped fresh', 'Substitution': '1 tablespoon chopped fresh parsley'},
    'Chicken base': {'Amount': '1 tablespoon', 'Substitution': '1 cup canned or homemade chicken broth or stock. Reduce liquid in recipe by 1 cup'},
    'Semisweet chocolate': {'Amount': '1 ounce', 'Substitution': '1 (1-ounce) square of unsweetened chocolate plus 4 teaspoons sugar OR 1 ounce semisweet chocolate chips plus 1 teaspoon shortening'},
    'Unsweetened chocolate': {'Amount': '1 ounce', 'Substitution': '3 tablespoons unsweetened cocoa plus 1 tablespoon shortening or vegetable oil'},
    'Cocoa': {'Amount': '1/4 cup', 'Substitution': '1 (1-ounce) square unsweetened chocolate'},
    'Condensed cream of mushroom soup': {'Amount': '1 (10.75-ounce) can', 'Substitution': '1 (10.75-ounce) can condensed cream of celery, cream of chicken, or golden mushroom soup'},
    'Corn syrup': {'Amount': '1 cup', 'Substitution': '1 1/4 cup white sugar plus 1/3 cup water OR 1 cup honey OR 1 cup light treacle syrup'},
    'Cottage cheese': {'Amount': '1 cup', 'Substitution': '1 cup farmer\'s cheese OR 1 cup ricotta cheese'},
    'Cracker crumbs': {'Amount': '1 cup', 'Substitution': '1 cup bread crumbs OR 1 cup matzo meal OR 1 cup ground oats'},
    'Half and Half': {'Amount': '1 cup', 'Substitution': '7/8 cup milk plus 1 tablespoon butter'},
    'Heavy Cream': {'Amount': '1 cup', 'Substitution': '1 cup evaporated milk OR 3/4 cup milk plus 1/3 cup butter'},
    'Light Cream': {'Amount': '1 cup', 'Substitution': '1 cup evaporated milk OR 3/4 cup milk plus 3 tablespoons butter'},
    'Whipped Cream': {'Amount': '1 cup', 'Substitution': '1 cup frozen whipped topping, thawed'},
    'Cream of tartar': {'Amount': '1 teaspoon', 'Substitution': '2 teaspoons lemon juice or vinegar'},
    'Creme fraiche': {'Amount': '1 cup', 'Substitution': 'Combine 1 cup of heavy cream and 1 tablespoon of plain yogurt. Let stand for 6 hours at room temperature'},
    'Egg': {'Amount': '1 whole (3 tablespoons or 1.7 oz)', 'Substitution': '2 1/2 tablespoons of powdered egg substitute plus 2 1/2 tablespoons water OR 1/4 cup liquid egg substitute OR 1/4 cup silken tofu pureed OR 3 tablespoons mayonnaise OR half a banana mashed with 1/2 teaspoon baking powder OR 1 tablespoon powdered flax seed soaked in 3 tablespoons water'},
    'Evaporated milk': {'Amount': '1 cup', 'Substitution': '1 cup light cream'},
    'Farmers cheese': {'Amount': '8 ounces', 'Substitution': '8 ounces dry cottage cheese OR 8 ounces creamed cottage cheese, drained'},
    'Baking fats': {'Amount': '1 cup', 'Substitution': '1 cup applesauce OR 1 cup fruit puree'},
    'Flour': {'Amount': '1 cup', 'Substitution': 'for bread: 1 cup all-purpose flour minus 2 tablespoons. For a cake: 1 cup all-purpose flour plus 1 teaspoon wheat gluten'},
    'self-rising Flour': {'Amount': '1 cup', 'Substitution': '7/8 cup all-purpose flour plus 1 1/2 teaspoons baking powder and 1/2 teaspoon of salt'},
    'Garlic': {'Amount': '1 clove', 'Substitution': '1/8 teaspoon garlic powder OR 1/2 teaspoon granulated garlic OR 1/2 teaspoon garlic salt, reduce salt in recipe'},
    'Gelatin': {'Amount': '1 tablespoon, granulated', 'Substitution': '2 teaspoons agar agar'},
    'Dry Ginger': {'Amount': '1 teaspoon', 'Substitution': '2 teaspoons chopped fresh ginger'},
    'Fresh ginger': {'Amount': '1 teaspoon, minced', 'Substitution': '1/2 teaspoon ground dried ginger'},
    'Green onion': {'Amount': '1/2 cup , chopped', 'Substitution': '1/2 cup chopped onion OR 1/2 cup chopped leek OR 1/2 cup chopped shallots'},
    'Hazelnuts': {'Amount': '1 cup whole', 'Substitution': '1 cup macadamia nuts OR 1 cup almonds'},
    'Herbs': {'Amount': '1 tablespoon chopped fresh', 'Substitution': '1 teaspoon (chopped or whole leaf) dried herbs'},
    'Herring': {'Amount': '8 ounces', 'Substitution': '8 ounces of sardines'},
    'Honey': {'Amount': '1 cup', 'Substitution': '1 1/4 cup white sugar plus 1/3 cup water OR 1 cup corn syrup OR 1 cup light treacle syrup'},
    'Hot pepper sauce': {'Amount': '1 teaspoon', 'Substitution': '3/4 teaspoon cayenne pepper plus 1 teaspoon vinegar'},
    'Lard': {'Amount': '1 cup', 'Substitution': '1 cup shortening OR 7/8 cup vegetable oil OR 1 cup butter'},
    'Lemon grass': {'Amount': '2 fresh stalks', 'Substitution': '1 tablespoon lemon zest'},
    'Lemon juice': {'Amount': '1 teaspoon', 'Substitution': '1/2 teaspoon vinegar OR 1 teaspoon white wine OR 1 teaspoon lime juice'},
    'Lemon zest': {'Amount': '1 teaspoon', 'Substitution': '1/2 teaspoon lemon extract OR 2 tablespoons lemon juice'},
    'Lime juice': {'Amount': '1 teaspoon', 'Substitution': '1 teaspoon vinegar OR 1 teaspoon white wine OR 1 teaspoon lemon juice'},
    'Lime zest': {'Amount': '1 teaspoon', 'Substitution': '1 teaspoon lemon zest'},
    'Macadamia nuts': {'Amount': '1 cup', 'Substitution': '1 cup almonds OR 1 cup hazelnuts'},
    'Mace': {'Amount': '1 teaspoon', 'Substitution': '1 teaspoon nutmeg'},
    'Margarine': {'Amount': '1 cup', 'Substitution': '1 cup shortening plus 1/2 teaspoon salt OR 1 cup butter OR 7/8 cup vegetable oil plus 1/2 teaspoon salt OR 7/8 cup lard plus 1/2 teaspoon salt'},
    'Mayonnaise': {'Amount': '1 cup', 'Substitution': '1 cup sour cream OR 1 cup plain yogurt'},
    'Whole milk': {'Amount': '1 cup', 'Substitution': '1 cup soy milk OR 1 cup rice milk OR 1 cup water or juice OR 1/4 cup dry milk powder plus 1 cup water OR 2/3 cup evaporated milk plus 1/3 cup water'},
    'Mint': {'Amount': '1/4 cup chopped', 'Substitution': '1 tablespoon dried mint leaves'},
    'Molasses': {'Amount': '1 cup', 'Substitution': 'Mix 3/4 cup brown sugar and 1 teaspoon cream of tartar'},
    'Mustard: prepared': {'Amount': '1 tablespoon', 'Substitution': 'Mix together 1 tablespoon dried mustard, 1 teaspoon water, 1 teaspoon vinegar and 1 teaspoon sugar'},
    'Onion': {'Amount': '1 cup, chopped', 'Substitution': '1 cup chopped green onions OR 1 cup chopped shallots OR 1 cup chopped leeks OR 1/4 cup dried minced onion OR 1/4 cup onion powder'},
    'Orange juice': {'Amount': '1 tablespoon', 'Substitution': '1 tablespoon other citrus juice'},
    'Orange zest': {'Amount': '1 tablespoon', 'Substitution': '1/2 teaspoon orange extract OR 1 teaspoon lemon juice'},
    'Parmesan cheese': {'Amount': '1/2 cup, grated', 'Substitution': '1/2 cup grated Asiago cheese OR 1/2 cup grated Romano cheese'},
    'Parsley': {'Amount': '1 tablespoon chopped fresh', 'Substitution': '1 tablespoon chopped fresh chervil OR 1 teaspoon dried parsley'},
    'Pepperoni': {'Amount': '1 ounce', 'Substitution': '1 ounce salami'},
    'Raisin': {'Amount': '1 cup', 'Substitution': '1 cup dried currants OR 1 cup dried cranberries OR 1 cup chopped pitted prunes'},
    'Rice': {'Amount': '1 cup, cooked', 'Substitution': '1 cup cooked barley OR 1 cup cooked bulgur OR 1 cup cooked brown, White or wild rice'},
    'Ricotta': {'Amount': '1 cup', 'Substitution': '1 cup dry cottage cheese OR 1 cup silken tofu'},
    'Rum': {'Amount': '1 tablespoon', 'Substitution': '1/2 teaspoon rum extract, plus enough water to make 1 tablespoon'},
    'Saffron': {'Amount': '1/4 teaspoon', 'Substitution': '1/4 teaspoon turmeric'},
    'Salami': {'Amount': '1 ounce', 'Substitution': '1 ounce pepperoni'},
    'Semisweet chocolate chips': {'Amount': '1 cup', 'Substitution': '1 cup chocolate candies OR 1 cup peanut butter or other flavored chips OR 1 cup chopped nuts OR 1 cup chopped dried fruit'},
    'Chopped shallots': {'Amount': '1/2 cup', 'Substitution': '1/2 cup chopped onion OR 1/2 cup chopped leek OR 1/2 cup chopped green onion'},
    'Shortening': {'Amount': '1 cup', 'Substitution': '1 cup butter OR 1 cup margarine minus 1/2 teaspoon salt from recipe'},
    'Sour cream': {'Amount': '1 cup', 'Substitution': '1 cup plain yogurt OR 1 tablespoon lemon juice or vinegar plus enough cream to make 1 cup OR 3/4 cup buttermilk mixed with 1/3 cup butter'},
    'Sour milk': {'Amount': '1 cup', 'Substitution': '1 tablespoon vinegar or lemon juice mixed with enough milk to make 1 cup: Let stand 5 minutes to thicken'},
    'Soy sauce': {'Amount': '1/2 cup', 'Substitution': '1/4 cup Worcestershire sauce mixed with 1 tablespoon water'},
    'Beef stock': {'Amount': '1 cup', 'Substitution': '1 cube beef or chicken bouillon dissolved in 1 cup water'},
    'Chicken stock': {'Amount': '1 cup', 'Substitution': '1 cube beef or chicken bouillon dissolved in 1 cup water'},
    'Sweetened condensed milk': {'Amount': '1 (14-ounce) can', 'Substitution': '3/4 cup white sugar mixed with 1/2 cup water and 1 1/8 cups dry powdered milk: Bring to a boil and cook, stirring frequently, until thickened, about 20 minutes'},
    'Vegetable oil': {'Amount': '1 cup', 'Substitution': 'For Baking: 1 cup applesauce OR 1 cup fruit puree. For Frying: 1 cup lard OR 1 cup vegetable shortening'},
    'Vinegar': {'Amount': '1 teaspoon', 'Substitution': '1 teaspoon lemon or lime juice OR 2 teaspoons white wine'},
    'White sugar': {'Amount': '1 cup', 'Substitution': '1 cup brown sugar OR 1 1/4 cups confectioners\' sugar OR 3/4 cup honey OR 3/4 cup corn syrup'},
    'Wine': {'Amount': '1 cup', 'Substitution': '1 cup chicken or beef broth OR 1 cup fruit juice mixed with 2 teaspoons vinegar OR 1 cup water'},
    'Active dry yeast': {'Amount': '1 (.25-ounce) package', 'Substitution': '1 cake compressed yeast OR 2 1/2 teaspoons active dry yeast OR 2 1/2 teaspoons rapid rise yeast'},
    'Yogurt': {'Amount': '1 cup', 'Substitution': '1 cup sour cream OR 1 cup buttermilk OR 1 cup sour milk'}
}

kitchen_tools = [
    'spoon',
    'fork',
    'knife',
    'spatula',
    'ladle',
    'whisk',
    'tongs',
    'grater',
    'peeler',
    'can opener',
    'bottle opener',
    'corkscrew',
    'scissors',
    'mixing bowl',
    'measuring cups',
    'measuring spoons',
    'cutting board',
    'colander',
    'strainer',
    'rolling pin',
    'pastry brush',
    'oven mitts',
    'pot holder',
    'kitchen shears',
    'grill brush',
    'basting brush',
    'pizza cutter',
    'ice cream scoop',
    'garlic press',
    'nutcracker',
    'egg slicer',
    'cheese slicer',
    'melon baller',
    'canister',
    'jar opener',
    'funnel',
    'salad spinner',
    'kitchen timer',
    'food thermometer',
    'baking dish',
    'roasting pan',
    'cake pan',
    'muffin tin',
    'baking sheet',
    'pie dish',
    'ramekins',
    'mixing spoons',
    'basting spoon',
    'slotted spoon',
    'skimmer',
    'soup ladle',
    'meat thermometer',
    'meat tenderizer',
    'potato masher',
    'potato peeler',
    'meat fork',
    'meat cleaver',
    'bread knife',
    'paring knife',
    'utility knife',
    'chef knife',
    'steak knives',
    'scalloped knife',
    'microplane grater',
    'spice grater',
    'zester',
    'fish scaler',
    'fish spatula',
    'skillet',
    'saucepan',
    'stockpot',
    'dutch oven',
    'wok',
    'roasting pan',
    'griddle',
    'paella pan',
    'frying pan',
    'saute pan',
    'double boiler',
    'baking dish',
    'casserole dish',
    'loaf pan',
    'bundt pan',
    'springform pan',
    'sheet pan',
    'muffin tin',
    'cake pan',
    'pie dish',
    'ramekins',
    'crockpot',
    'rice cooker',
    'slow cooker',
    'pressure cooker',
    'grill pan',
    'smoker',
    'stovetop griddle',
    'electric griddle',
    'grill basket',
    'stir fry pan',
    'tagine',
    'fondue pot',
    'bean pot',
    'tajine',
    'broiler pan',
    'brazier',
    'chafing dish',
    'fryer',
    'popcorn maker',
    'crepe pan',
    'milk frother',
    'moka pot',
    'espresso machine',
    'coffee maker',
    'tea kettle',
    'blender',
    'food processor',
    'stand mixer',
    'hand mixer',
    'immersion blender',
    'juicer',
    'citrus juicer',
    'food chopper',
    'meat grinder',
    'bread maker',
    'toaster',
    'microwave oven',
    'gas range',
    'electric range',
    'oven',
    'cooktop',
    'hood',
    'dishwasher',
    'refrigerator',
    'freezer',
    'wine cooler',
    'trash can',
    'kitchen island',
    'pantry',
    'utensil holder',
    'knife block',
    'cutting board',
    'dish rack',
    'pot rack',
    'apron',
    'oven mitts',
    'pot holder',
    'dish towels'
]
# Meat: beef, chicken, pork, lamb, turkey, duck, venison, rabbit, bison, goat, veal, boar, camel.
# Fish: salmon, tuna, cod, halibut, trout, mackerel, sardines, tilapia, catfish, sea bass, snapper, swordfish, and haddock.
# Seafood: shrimp, crab, lobster, scallops, clams, oysters, and mussels.
# Organ meats: liver, heart, kidney, and tripe.
# Deli meats: ham, turkey, roast beef, pastrami, corned beef, and salami.
# Sausages: bratwurst, chorizo, andouille, kielbasa, Italian sausage, and breakfast sausage, sausage.

#Tofu
#Tempeh
#Seitan (also known as wheat meat or wheat gluten)
#Legumes (e.g. lentils, chickpeas, black beans)
#Mushrooms (e.g. portobello, shiitake)
#Quorn (a type of mycoprotein)
#Textured vegetable protein (TVP)
#Nutritional yeast (a source of vegan protein and B vitamins)
#Eggplant
#Jackfruit
#Beyond patty
#Tofu dog

veg_substitutes = ['tofu', 'tempeh', 'seitan', 'jackfruit', 'lentils', 'chickpeas', 'Beyond patty']

meats = {
    "Meat": [ "beef", "chicken", "pork", "lamb", "turkey", "duck", "venison", "rabbit", "bison", "goat", "veal", "boar", "camel"],
    "Fish": [ "salmon", "tuna", "cod", "halibut", "trout", "mackerel", "sardines", "tilapia", "catfish", "sea bass", "snapper", "swordfish", "haddock"],
    "Seafood": [ "shrimp", "crab", "lobster", "scallops", "clams", "oysters", "mussels"],
    "Organ": [ "liver", "heart", "kidney", "tripe", "sweetbread", "foie", "brain"],
    "Deli": [ "ham", "turkey", "roast beef", "pastrami", "corned beef", "salami"],
    "Sausages": [ "bratwurst", "chorizo", "andouille", "kielbasa", "Italian sausage", "breakfast sausage", "sausage"]
}

spices = ['cumin', 'coriander', 'turmeric', 'garam masala', 'cardamom',
    'cumin', 'chili powder', 'oregano', 'paprika', 'cayenne',
    'basil', 'oregano', 'garlic', 'thyme', 'rosemary',
    'ginger', 'garlic', 'star anise', 'five-spice', 'Szechuan pepper',
    'lemongrass', 'galangal', 'coriander', 'cumin', 'chili',
    'oregano', 'thyme', 'garlic', 'cinnamon', 'mint',
    'thyme', 'tarragon', 'rosemary', 'lavender', 'sage',
    'allspice', 'nutmeg', 'black pepper', 'thyme', 'cayenne', 'paprika','garlic', 'ginger',
    'paprika', 'mustard powder', 'black pepper', 'oregano', 'cumin', 'caraway', 'red pepper', 'cayenne',
    'soy sauce', 'mirin', 'ginger', 'wasabi', 'sesame',
    'gochujang', 'garlic', 'ginger', 'sesame oil', 'soy sauce',
    'lemongrass', 'star anise', 'cinnamon', 'coriander', 'fish sauce',
    'paprika', 'saffron', 'garlic', 'oregano', 'cumin',
    'cumin', 'coriander', 'cinnamon', 'paprika', 'turmeric',
    'allspice', 'nutmeg', 'thyme', 'cumin', 'cinnamon',
    'berbere', 'cardamom', 'cumin', 'fenugreek', 'paprika',
    'cumin', 'sumac', 'mint', 'paprika', 'coriander',
    'cumin', 'coriander', 'sumac', 'cinnamon', 'mint',
    'dill', 'mustard', 'coriander', 'bay leaf', 'paprika',
    'lemongrass', 'galangal', 'coriander', 'cumin', 'turmeric',
    'saffron', 'turmeric', 'cumin', 'coriander', 'cardamom',
    'cumin', 'coriander', 'paprika', 'ginger', 'cardamom',
    'sumac', 'za\'atar', 'turmeric', 'cumin', 'paprika',
    'paprika', 'bay leaf', 'cumin', 'cinnamon', 'cloves',
    'paprika', 'cumin', 'oregano', 'bay leaf', 'coriander',
    'aji amarillo', 'cumin', 'coriander', 'oregano', 'paprika',
    'garlic', 'onion', 'bay leaf', 'black pepper', 'lemongrass',
    'lemongrass', 'turmeric', 'galangal', 'coriander', 'cumin',
    'turmeric', 'lemongrass', 'galangal', 'coriander', 'cumin',
    'cumin', 'coriander', 'curry leaves', 'fenugreek', 'mustard seeds',
    'ginger', 'garlic', 'onion', 'cumin', 'cayenne',
    'dill', 'allspice', 'cinnamon', 'cloves', 'cardamom',
    'allspice', 'cloves', 'cinnamon', 'bay leaf', 'black pepper']

cuisine_spices = {
    'Indian': ['cumin', 'coriander', 'turmeric', 'garam masala', 'cardamom'],
    'Mexican': ['cumin', 'chili powder', 'oregano', 'paprika', 'cayenne'],
    'Italian': ['basil', 'oregano', 'garlic', 'thyme', 'rosemary'],
    'Chinese': ['ginger', 'garlic', 'star anise', 'five-spice', 'Szechuan pepper'],
    'Thai': ['lemongrass', 'galangal', 'coriander', 'cumin', 'chili'],
    'Greek': ['oregano', 'thyme', 'garlic', 'cinnamon', 'mint'],
    'French': ['thyme', 'tarragon', 'rosemary', 'lavender', 'sage'],
    'jamaican':['allspice', 'nutmeg', 'black pepper', 'thyme', 'cayenne', 'paprika','garlic', 'ginger'],
    'cajun':['paprika', 'mustard powder', 'black pepper', 'oregano', 'cumin', 'caraway', 'red pepper', 'cayenne'],
    'Japanese': ['soy sauce', 'mirin', 'ginger', 'wasabi', 'sesame'],
    'Korean': ['gochujang', 'garlic', 'ginger', 'sesame oil', 'soy sauce'],
    'Vietnamese': ['lemongrass', 'star anise', 'cinnamon', 'coriander', 'fish sauce'],
    'Spanish': ['paprika', 'saffron', 'garlic', 'oregano', 'cumin'],
    'Moroccan': ['cumin', 'coriander', 'cinnamon', 'paprika', 'turmeric'],
    'Caribbean': ['allspice', 'nutmeg', 'thyme', 'cumin', 'cinnamon'],
    'Ethiopian': ['berbere', 'cardamom', 'cumin', 'fenugreek', 'paprika'],
    'Turkish': ['cumin', 'sumac', 'mint', 'paprika', 'coriander'],
    'Lebanese': ['cumin', 'coriander', 'sumac', 'cinnamon', 'mint'],
    'Russian': ['dill', 'mustard', 'coriander', 'bay leaf', 'paprika'],
    'Indonesian': ['lemongrass', 'galangal', 'coriander', 'cumin', 'turmeric'],
    'Iranian': ['saffron', 'turmeric', 'cumin', 'coriander', 'cardamom'],
    'Afghan': ['cumin', 'coriander', 'paprika', 'ginger', 'cardamom'],
    'Israeli': ['sumac', 'za\'atar', 'turmeric', 'cumin', 'paprika'],
    'Portuguese': ['paprika', 'bay leaf', 'cumin', 'cinnamon', 'cloves'],
    'Brazilian': ['paprika', 'cumin', 'oregano', 'bay leaf', 'coriander'],
    'Peruvian': ['aji amarillo', 'cumin', 'coriander', 'oregano', 'paprika'],
    'Filipino': ['garlic', 'onion', 'bay leaf', 'black pepper', 'lemongrass'],
    'Cambodian': ['lemongrass', 'turmeric', 'galangal', 'coriander', 'cumin'],
    'Malaysian': ['turmeric', 'lemongrass', 'galangal', 'coriander', 'cumin'],
    'Sri Lankan': ['cumin', 'coriander', 'curry leaves', 'fenugreek', 'mustard seeds'],
    'Nigerian': ['ginger', 'garlic', 'onion', 'cumin', 'cayenne'],
    'Swedish': ['dill', 'allspice', 'cinnamon', 'cloves', 'cardamom'],
    'Scottish': ['allspice', 'cloves', 'cinnamon', 'bay leaf', 'black pepper']
}

cuisine_meats = {
    'Italian': ['beef', 'pork', 'chicken', 'sausage', 'prosciutto'],
    'Mexican': ['beef', 'pork', 'chicken', 'chorizo', 'carne asada'],
    'Indian': ['chicken', 'lamb', 'goat', 'fish', 'shrimp'],
    'Japanese': ['beef', 'pork', 'chicken', 'seafood', 'tofu'],
    'Thai': ['beef', 'pork', 'chicken', 'shrimp', 'crab'],
    'Chinese': ['pork', 'chicken', 'beef', 'duck', 'seafood'],
    'Greek': ['lamb', 'pork', 'chicken', 'beef', 'goat'],
    'Korean': ['beef', 'pork', 'chicken', 'tofu', 'octopus'],
    'Vietnamese': ['beef', 'pork', 'chicken', 'shrimp', 'fish'],
    'Brazilian': ['beef', 'pork', 'chicken', 'sausage', 'lamb'],
    'American': ['beef', 'pork', 'chicken', 'turkey', 'bacon'],
    'French': ['beef', 'pork', 'chicken', 'duck', 'lamb'],
    'Spanish': ['pork', 'chicken', 'beef', 'chorizo', 'seafood'],
    'Caribbean': ['chicken', 'pork', 'beef', 'goat', 'seafood'],
    'Turkish': ['beef', 'lamb', 'chicken', 'turkey', 'veal'],
    'Lebanese': ['beef', 'lamb', 'chicken', 'shawarma', 'kebab'],
    'Moroccan': ['beef', 'lamb', 'chicken', 'camel', 'pigeon'],
    'Russian': ['beef', 'pork', 'chicken', 'venison', 'moose'],
    'Irish': ['beef', 'lamb', 'pork', 'sausage', 'bacon'],
    'German': ['pork', 'beef', 'chicken', 'sausage', 'veal'],
    'Swiss': ['beef', 'pork', 'chicken', 'venison', 'game birds'],
    'Austrian': ['pork', 'beef', 'veal', 'sausage', 'duck'],
    'Canadian': ['beef', 'pork', 'chicken', 'wild game', 'salmon'],
    'Cajun': ['sausage', 'chicken', 'andouille', 'crawfish', 'shrimp'],
    'Indonesian': ['chicken', 'beef', 'pork', 'fish', 'tofu'],
    'Bangladeshi': ['beef', 'chicken', 'mutton', 'fish', 'prawn'],
    'Egyptian': ['lamb', 'beef', 'chicken', 'pigeon', 'fish'],
    'Ethiopian': ['beef', 'lamb', 'chicken', 'goat', 'fish']
}

#Health substutions:
healthy_subs = {
    "cream cheese": "light cream cheese",
    "sour cream": "greek yogurt",
    "milk": "almond milk",
    "butter": "olive oil",
    "cheese": "fat free cheese",
    "cream": "low fat milk",
    "whole milk": "low fat milk",
    "beef broth": "mushroom broth",
    "bacon": "ham",
    "ground beef": "ground turkey",
    "sausage": "turkey sausage",
    "egg": "egg white",
    "flour tortilla": "corn tortilla",
    "rice": "cauliflower rice",
    "potato": "sweet potato",
    "chocolate": "dark chocolate",
    "sugar": "stevia",
    "mayonnaise": "light mayonnaise",
    "hot dog": "turkey dog",
    "potato": "squash",
    "chickpeas":"soy beans",
    "oil": "olive oil",
    "sesame oil": "olive oil",
    "vegetable oil": "olive oil",
    "granola": "oatmeal",
    "pasta": "whole wheat pasta",
    "pepperoni": "ham",
    "crackers":"carrots",
	"chips":"carrots",
	"beef":"lean beef",
	"bread":"whole wheat bread",
	"chicken":"skinless chicken breast",
	"fudge":"low fat syrup",
	"bun":"lettuce wrap",
	"biscuits":"whole wheat biscuits",
	"beans":"soy beans",
	"flour":"whole wheat flower",
	"cereal":"oatmeal",
}

unhealthy_subs = {
    "light cream cheese": "cream cheese",
    "yogurt": "sour cream",
    "milk": "cream",
    "olive oil": "butter",
    "fat free cheese": "cheese",
    "lettuce wrap": "bun", 
    "whole wheat": " ",
    "stevia": "sugar",
    "chicken broth": "beef broth",
    "mushroom broth": "beef broth",
    "low fat milk": "cream",
    "turkey": "beef",
    "ham": "bacon",
    "oatmeal": "cereal",
    "ground turkey": "ground beef",
    "chicken": "pork",
    "turkey sausage": "sausage",
    "egg white": "egg",
    "corn tortilla": "flour tortilla",
    "cauliflower rice": "rice",
    "sweet potato": "potato",
    "dark chocolate": "milk chocolate",
    "stevia": "sugar",
    "light mayonnaise": "mayonnaise",
    "turkey dog": "hot dog",
    "zucchini": "potato",
    "olive oil": "sesame oil",
    "oatmeal": "granola",
    "whole wheat pasta": "pasta",
    "ham": "pepperoni",
    "salmon steaks": "tuna steaks", 
    "sesame oil": "butter",
    "low fat": " ", 

}